### ISSUE TITLE
编译指引 Building Guide

### ISSUE THREAD

**Issue by wangyonghui0394** [OrayOS/OpenOray#3]
OpenWRT 20.02版本已经找不到镜像，官方可以出个build教程吗？
Image of OpenWRT version 20.02 is not found, could Oray publish an guide how to build orayvpn?

**Comment by lintel** [comment]
请稍等，官网文档已经在进行更新。

**Comment by aiamadeus** [comment]
Please refer to https://service.oray.com/question/20529.html

**Comment by wangyonghui0394** [comment]
Thanks for your support.

**Comment by wangyonghui0394** [comment]
越做越强
